# Connections API v√©lo

## Connector

In [1]:
import json
import requests
import pandas as pd

class api_connector():
    def get_api(self,url):
        response = requests.request("GET",url)
        response_json = json.loads(response.text.encode('utf-8'))
        return response_json.get("records",[])
    
    def get_lille(self):
        url = "https://opendata.lillemetropole.fr/api/records/1.0/search/?dataset=vlille-realtime&q=&rows=2000&facet=libelle&facet=nom&facet=commune&facet=etat&facet=type&facet=etatconnexion"
        return self.get_api(url)
    
    def get_rennes(self):
        url = "https://data.rennesmetropole.fr/api/records/1.0/search/?dataset=etat-des-stations-le-velo-star-en-temps-reel&q=&rows=2000&facet=nom&facet=etat&facet=nombreemplacementsactuels&facet=nombreemplacementsdisponibles&facet=nombrevelosdisponibles"
        return self.get_api(url)
    
    def get_lyon(self):
        url = "https://public.opendatasoft.com/api/records/1.0/search/?dataset=station-velov-grand-lyon&q=&rows=2000&facet=name&facet=commune&facet=bonus&facet=status&facet=available&facet=availabl_1&facet=availabili&facet=availabi_1&facet=last_upd_1"
        return self.get_api(url)
    
    def get_paris(self):
        url = "https://opendata.paris.fr/api/records/1.0/search/?dataset=velib-disponibilite-en-temps-reel&q=&rows=2000&facet=name&facet=is_installed&facet=is_renting&facet=is_returning&facet=nom_arrondissement_communes"
        return self.get_api(url)

In [2]:
ac = api_connector()

In [3]:
pd.set_option('display.max_columns', None)

### Lille

In [4]:
dflille = pd.json_normalize(ac.get_lille())
dflille.head()

,datasetid,recordid,record_timestamp,fields.etat,fields.etatconnexion,fields.nbvelosdispo,fields.nbplacesdispo,fields.commune,fields.type,fields.libelle,fields.datemiseajour,fields.localisation,fields.nom,fields.adresse,fields.geo,geometry.type,geometry.coordinates
0,vlille-realtime,e262deb6bdf2bd339975697487646055c99a511f,2020-10-12T10:24:05.094000+00:00,EN SERVICE,CONNECTED,2,14,LILLE,AVEC TPE,164,2020-10-12T10:23:05+00:00,"[50.63393, 3.061687]",HOPITAL MILITAIRE,2 RUE PIERRE DUPONT,"[50.63393, 3.061687]",Point,"[3.061687, 50.63393]"
1,vlille-realtime,18b269166d31afbff1eaa73ca676067639cdbec7,2020-10-12T10:24:05.094000+00:00,EN SERVICE,CONNECTED,11,13,LILLE,AVEC TPE,19,2020-10-12T10:23:04+00:00,"[50.64031, 3.05774]",RUE ROYALE,40 RUE ROYALE,"[50.64031, 3.05774]",Point,"[3.05774, 50.64031]"
2,vlille-realtime,e0676f038aea52b64945ef7be8b52c74ae89ba6f,2020-10-12T10:24:05.094000+00:00,EN SERVICE,CONNECTED,19,17,LILLE,AVEC TPE,27,2020-10-12T10:23:04+00:00,"[50.635014, 3.064802]",TANNEURS,2 - 10 RUE DES TANNEURS,"[50.635014, 3.064802]",Point,"[3.064802, 50.635014]"
3,vlille-realtime,81cdd1ead280be51a8e0868793eb13118621056f,2020-10-12T10:24:05.094000+00:00,EN SERVICE,CONNECTED,2,18,LILLE,AVEC TPE,29,2020-10-12T10:23:04+00:00,"[50.647236, 3.059376]",ST SEBASTIEN,40 RUE SAINT SEBASTIEN,"[50.647236, 3.059376]",Point,"[3.059376, 50.647236]"
4,vlille-realtime,e76138729b09a25cec4020ec405ca46807ef3d1d,2020-10-12T10:24:05.094000+00:00,EN SERVICE,CONNECTED,9,3,LILLE,SANS TPE,172,2020-10-12T10:23:05+00:00,"[50.612635, 3.059261]",PLACE DE LA GARONNE,Rue de la Seine,"[50.612635, 3.059261]",Point,"[3.059261, 50.612635]"

In [5]:
for col in dflille:
    print (col)

datasetid
recordid
record_timestamp
fields.etat
fields.etatconnexion
fields.nbvelosdispo
fields.nbplacesdispo
fields.commune
fields.type
fields.libelle
fields.datemiseajour
fields.localisation
fields.nom
fields.adresse
fields.geo
geometry.type
geometry.coordinates

### Rennes

In [6]:
dfrennes = pd.json_normalize(ac.get_rennes())
dfrennes.head()

,datasetid,recordid,record_timestamp,fields.etat,fields.lastupdate,fields.nombrevelosdisponibles,fields.nombreemplacementsactuels,fields.nom,fields.nombreemplacementsdisponibles,fields.idstation,fields.coordonnees,geometry.type,geometry.coordinates
0,etat-des-stations-le-velo-star-en-temps-reel,88a8871cd455b991aae541e2d60ebdab34840e3e,2020-10-12T10:23:00+00:00,En fonctionnement,2020-10-12T10:23:08+00:00,12.0,16.0,Mus√©e Beaux-Arts,4.0,5510,"[48.109601, -1.67408]",Point,"[-1.67408, 48.109601]"
1,etat-des-stations-le-velo-star-en-temps-reel,b476b4248e499552a1449cb8afe72cc68c83c060,2020-10-12T10:23:00+00:00,En fonctionnement,2020-10-12T10:23:08+00:00,13.0,24.0,Champs Libres,11.0,5516,"[48.105537, -1.674328]",Point,"[-1.674328, 48.105537]"
2,etat-des-stations-le-velo-star-en-temps-reel,bd0f83abcec2974fda4a9be7b78f4bfbb3af4b27,2020-10-12T10:23:00+00:00,En fonctionnement,2020-10-12T10:23:08+00:00,18.0,24.0,Brest - Verdun,6.0,5534,"[48.113009, -1.693264]",Point,"[-1.693264, 48.113009]"
3,etat-des-stations-le-velo-star-en-temps-reel,bc23b982c96a853bb90665c1d574e7d9c204daed,2020-10-12T10:23:00+00:00,En fonctionnement,2020-10-12T10:23:08+00:00,7.0,20.0,Marbeuf,13.0,5538,"[48.111749, -1.702077]",Point,"[-1.702077, 48.111749]"
4,etat-des-stations-le-velo-star-en-temps-reel,77cac0a1ecd7f2af56c8668b201afe2a20e1c6bb,2020-10-12T10:23:00+00:00,En fonctionnement,2020-10-12T10:23:08+00:00,17.0,24.0,Plaine de Baud,7.0,5546,"[48.112461, -1.643674]",Point,"[-1.643674, 48.112461]"

In [7]:
for col in dfrennes:
    print (col)

datasetid
recordid
record_timestamp
fields.etat
fields.lastupdate
fields.nombrevelosdisponibles
fields.nombreemplacementsactuels
fields.nom
fields.nombreemplacementsdisponibles
fields.idstation
fields.coordonnees
geometry.type
geometry.coordinates

### Lyon

In [8]:
dflyon = pd.json_normalize(ac.get_lyon())
dflyon.head()

,datasetid,recordid,record_timestamp,fields.available,fields.status,fields.availabl_1,fields.name,fields.commune,fields.bonus,fields.last_updat,fields.address,fields.bike_stand,fields.geo_point_2d,fields.availabili,fields.number,fields.banking,fields.gid,fields.nmarrond,fields.lat,fields.geo_shape.type,fields.geo_shape.coordinates,fields.lng,fields.availabi_1,fields.last_upd_1,geometry.type,geometry.coordinates,fields.pole,fields.address2
0,station-velov-grand-lyon,35a35fa3d3108e1305d37c7f7218897842a2a7ab,2019-03-12T10:20:50.428000+00:00,23,OPEN,12,ZAC de la Buire,Lyon 3 √®me,Non,2015-07-01 16:08:47,Face au 106 avenue F√©lix Faure,35,"[45.75379945822723, 4.859863339774901]",1,3036,t,952,36,45.7537994582273000,Point,"[4.859863339774901, 45.75379945822723]",4.8598633397749000,Vert,2015-07-01 16:11:00,Point,"[4.859863339774901, 45.75379945822723]",NaN,NaN
1,station-velov-grand-lyon,ee303eaa5ac1406821f4186a2118cb9b27005ae5,2019-03-12T10:20:50.428000+00:00,4,OPEN,16,Brotteaux,Lyon 6 √®me,Non,2015-07-01 16:04:00,17 place Jules Ferry,20,"[45.768412261376376, 4.859070556738342]",1,6008,t,938,8,45.7684122613765000,Point,"[4.859070556738342, 45.768412261376376]",4.8590705567383400,Vert,2015-07-01 16:11:00,Point,"[4.859070556738342, 45.768412261376376]","M√©tro, parking, place, restaurants",NaN
2,station-velov-grand-lyon,6763bd64aa006ea3a8855e24f303f979a45e3b95,2019-03-12T10:20:50.428000+00:00,12,OPEN,6,Place Sainte Anne,Lyon 3 √®me,Non,2015-07-01 16:05:24,2 place Saint Anne,18,"[45.75695497472745, 4.865441659195344]",1,3099,t,940,99,45.7569549747275000,Point,"[4.865441659195344, 45.75695497472745]",4.8654416591953500,Vert,2015-07-01 16:11:00,Point,"[4.865441659195344, 45.75695497472745]","Coeur de quartier, commerces",NaN
3,station-velov-grand-lyon,c97904e4102ccaa62a939918d280bc81856418cd,2019-03-12T10:20:50.428000+00:00,7,OPEN,9,Lafayette / Cr√©qui,Lyon 3 √®me,Non,2015-07-01 16:02:04,Rue de Cr√©qui,16,"[45.76340457257395, 4.847137408952479]",1,3032,t,868,32,45.7634045725740000,Point,"[4.847137408952479, 45.76340457257395]",4.8471374089524800,Vert,2015-07-01 16:11:00,Point,"[4.847137408952479, 45.76340457257395]",NaN,Angle cours Lafayette
4,station-velov-grand-lyon,64d00c6c5b0b212af83a7fccc3d6a90f79d4d783,2019-03-12T10:20:50.428000+00:00,0,CLOSED,0,Pr√©ssens√© / 8 mai 1945,VILLEURBANNE,Non,2015-07-01 16:07:03,"294, rue Francis de Pr√©ssens√©",16,"[45.76918019445715, 4.896723707091346]",0,10049,t,869,49,45.7691801944572000,Point,"[4.896723707091346, 45.76918019445715]",4.8967237070913500,Gris,2015-07-01 16:11:00,Point,"[4.896723707091346, 45.76918019445715]",itin√©raires cyclables,NaN

In [9]:
for col in dflyon:
    print (col)

datasetid
recordid
record_timestamp
fields.available
fields.status
fields.availabl_1
fields.name
fields.commune
fields.bonus
fields.last_updat
fields.address
fields.bike_stand
fields.geo_point_2d
fields.availabili
fields.number
fields.banking
fields.gid
fields.nmarrond
fields.lat
fields.geo_shape.type
fields.geo_shape.coordinates
fields.lng
fields.availabi_1
fields.last_upd_1
geometry.type
geometry.coordinates
fields.pole
fields.address2

### Paris

In [10]:
dfparis = pd.json_normalize(ac.get_paris())
dfparis.head()

,datasetid,recordid,record_timestamp,fields.ebike,fields.capacity,fields.name,fields.nom_arrondissement_communes,fields.numbikesavailable,fields.is_installed,fields.is_renting,fields.mechanical,fields.stationcode,fields.coordonnees_geo,fields.numdocksavailable,fields.duedate,fields.is_returning,geometry.type,geometry.coordinates
0,velib-disponibilite-en-temps-reel,feab4f8a417ac98699937147a1b081a1feefabe3,2020-10-12T10:24:07.026000+00:00,11,55,Andr√© Mazet - Saint-Andr√© des Arts,Paris,47,OUI,OUI,36,6015,"[48.8537558106, 2.33909580857]",6,2020-10-12T10:16:06+00:00,OUI,Point,"[2.33909580857, 48.8537558106]"
1,velib-disponibilite-en-temps-reel,38c4bffd98e935349194a1f258f1f9a5a45827de,2020-10-12T10:24:07.026000+00:00,3,20,Charonne - Robert et Sonia Delauney,Paris,3,OUI,OUI,0,11104,"[48.855907556, 2.39257067442]",17,2020-10-12T10:16:06+00:00,OUI,Point,"[2.39257067442, 48.855907556]"
2,velib-disponibilite-en-temps-reel,7c48eb073523e7c25f34d96eb7585076951f5dce,2020-10-12T10:24:07.026000+00:00,2,60,Jourdan - Stade Charl√©ty,Paris,2,OUI,OUI,0,14014,"[48.8194283334, 2.34333537519]",58,2020-10-12T10:11:00+00:00,OUI,Point,"[2.34333537519, 48.8194283334]"
3,velib-disponibilite-en-temps-reel,73ba612bf52c18550c44b42398f086d0b7d5b417,2020-10-12T10:24:07.026000+00:00,2,40,Jouffroy d'Abbans - Wagram,Paris,3,OUI,OUI,1,17026,"[48.8819732984, 2.30113215744]",37,2020-10-12T10:15:22+00:00,OUI,Point,"[2.30113215744, 48.8819732984]"
4,velib-disponibilite-en-temps-reel,08598bb989ab55f38f3094df02335634ca858287,2020-10-12T10:24:07.026000+00:00,0,39,Guersant - Gouvion-Saint-Cyr,Paris,3,OUI,OUI,3,17041,"[48.8828777518, 2.28766737081]",35,2020-10-12T10:10:45+00:00,OUI,Point,"[2.28766737081, 48.8828777518]"

In [11]:
for col in dfparis:
    print (col)

datasetid
recordid
record_timestamp
fields.ebike
fields.capacity
fields.name
fields.nom_arrondissement_communes
fields.numbikesavailable
fields.is_installed
fields.is_renting
fields.mechanical
fields.stationcode
fields.coordonnees_geo
fields.numdocksavailable
fields.duedate
fields.is_returning
geometry.type
geometry.coordinates

## Clean

On nettoie les datasets pour les placer dans la collection d'abri √† v√©lo avec les informations suivantes:

geolocations, size, name, tpe, available

In [12]:
def clean_lille(dflille):
    dflilleclean = dflille[['fields.nom','fields.geo','fields.type','fields.etat']].drop_duplicates(subset=['fields.nom'])
    dflilleclean = dflilleclean.rename(columns={'fields.nom':'Name','fields.geo':'Geo','fields.type':'TPE','fields.etat':'Available'})
    
    # get the size of Lille Stations by adding the number of availables places and bicycles
    size = []
    for i, row in dflille.iterrows():
        size.append(row['fields.nbvelosdispo']+row['fields.nbplacesdispo'])

    dflilleclean = pd.concat([dflilleclean,pd.DataFrame(size, columns = ['Size'])], axis=1, join='inner')

    # set the 'tpe' column with boolean
    dflilleclean['TPE'] = dflilleclean['TPE'].replace("AVEC TPE","True")
    dflilleclean['TPE'] = dflilleclean['TPE'].replace("SANS TPE","False")

    # set the 'Available' column with boolean
    dflilleclean['Available'] = dflilleclean['Available'].replace("EN SERVICE","True")

    for i, row in dflilleclean.iterrows():
        if not row['Available'] == 'True':
            dflilleclean['Available'].loc[i] = 'False'
            
    return(dflilleclean)

dflilleclean = clean_lille(dflille)
dflilleclean.head()

C:\Users\avere\.conda\envs\velomongo\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

                  Name                    Geo    TPE Available  Size
0    HOPITAL MILITAIRE   [50.63393, 3.061687]   True      True    16
1           RUE ROYALE    [50.64031, 3.05774]   True      True    24
2             TANNEURS  [50.635014, 3.064802]   True      True    36
3         ST SEBASTIEN  [50.647236, 3.059376]   True      True    20
4  PLACE DE LA GARONNE  [50.612635, 3.059261]  False      True    12

In [13]:
def clean_rennes(dfrennes):
    dfrennesclean = dfrennes[["fields.nom","fields.coordonnees","fields.etat","fields.nombreemplacementsactuels"]].drop_duplicates(subset=['fields.nom'])
    dfrennesclean = dfrennesclean.rename(columns={'fields.nom':'Name','fields.coordonnees':'Geo','fields.type':'TPE','fields.etat':'Available','fields.nombreemplacementsactuels':'Size'})

    # set the 'Available' column with boolean
    dfrennesclean['Available'] = dfrennesclean['Available'].replace("En fonctionnement","True")

    for i, row in dfrennesclean.iterrows():
        if not row['Available'] == 'True':
            dfrennesclean['Available'].loc[i] = 'False'
        
    return(dfrennesclean)

dfrennesclean = clean_rennes(dfrennes)
dfrennesclean.head()

C:\Users\avere\.conda\envs\velomongo\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

               Name                     Geo Available  Size
0  Mus√©e Beaux-Arts   [48.109601, -1.67408]      True  16.0
1     Champs Libres  [48.105537, -1.674328]      True  24.0
2    Brest - Verdun  [48.113009, -1.693264]      True  24.0
3           Marbeuf  [48.111749, -1.702077]      True  20.0
4    Plaine de Baud  [48.112461, -1.643674]      True  24.0

In [14]:
dflyon.head()

,datasetid,recordid,record_timestamp,fields.available,fields.status,fields.availabl_1,fields.name,fields.commune,fields.bonus,fields.last_updat,fields.address,fields.bike_stand,fields.geo_point_2d,fields.availabili,fields.number,fields.banking,fields.gid,fields.nmarrond,fields.lat,fields.geo_shape.type,fields.geo_shape.coordinates,fields.lng,fields.availabi_1,fields.last_upd_1,geometry.type,geometry.coordinates,fields.pole,fields.address2
0,station-velov-grand-lyon,35a35fa3d3108e1305d37c7f7218897842a2a7ab,2019-03-12T10:20:50.428000+00:00,23,OPEN,12,ZAC de la Buire,Lyon 3 √®me,Non,2015-07-01 16:08:47,Face au 106 avenue F√©lix Faure,35,"[45.75379945822723, 4.859863339774901]",1,3036,t,952,36,45.7537994582273000,Point,"[4.859863339774901, 45.75379945822723]",4.8598633397749000,Vert,2015-07-01 16:11:00,Point,"[4.859863339774901, 45.75379945822723]",NaN,NaN
1,station-velov-grand-lyon,ee303eaa5ac1406821f4186a2118cb9b27005ae5,2019-03-12T10:20:50.428000+00:00,4,OPEN,16,Brotteaux,Lyon 6 √®me,Non,2015-07-01 16:04:00,17 place Jules Ferry,20,"[45.768412261376376, 4.859070556738342]",1,6008,t,938,8,45.7684122613765000,Point,"[4.859070556738342, 45.768412261376376]",4.8590705567383400,Vert,2015-07-01 16:11:00,Point,"[4.859070556738342, 45.768412261376376]","M√©tro, parking, place, restaurants",NaN
2,station-velov-grand-lyon,6763bd64aa006ea3a8855e24f303f979a45e3b95,2019-03-12T10:20:50.428000+00:00,12,OPEN,6,Place Sainte Anne,Lyon 3 √®me,Non,2015-07-01 16:05:24,2 place Saint Anne,18,"[45.75695497472745, 4.865441659195344]",1,3099,t,940,99,45.7569549747275000,Point,"[4.865441659195344, 45.75695497472745]",4.8654416591953500,Vert,2015-07-01 16:11:00,Point,"[4.865441659195344, 45.75695497472745]","Coeur de quartier, commerces",NaN
3,station-velov-grand-lyon,c97904e4102ccaa62a939918d280bc81856418cd,2019-03-12T10:20:50.428000+00:00,7,OPEN,9,Lafayette / Cr√©qui,Lyon 3 √®me,Non,2015-07-01 16:02:04,Rue de Cr√©qui,16,"[45.76340457257395, 4.847137408952479]",1,3032,t,868,32,45.7634045725740000,Point,"[4.847137408952479, 45.76340457257395]",4.8471374089524800,Vert,2015-07-01 16:11:00,Point,"[4.847137408952479, 45.76340457257395]",NaN,Angle cours Lafayette
4,station-velov-grand-lyon,64d00c6c5b0b212af83a7fccc3d6a90f79d4d783,2019-03-12T10:20:50.428000+00:00,0,CLOSED,0,Pr√©ssens√© / 8 mai 1945,VILLEURBANNE,Non,2015-07-01 16:07:03,"294, rue Francis de Pr√©ssens√©",16,"[45.76918019445715, 4.896723707091346]",0,10049,t,869,49,45.7691801944572000,Point,"[4.896723707091346, 45.76918019445715]",4.8967237070913500,Gris,2015-07-01 16:11:00,Point,"[4.896723707091346, 45.76918019445715]",itin√©raires cyclables,NaN

In [15]:
def clean_lyon(dflyon):
    dflyonclean = dflyon[["fields.name","fields.geo_shape.coordinates","fields.status","fields.bike_stand"]].drop_duplicates(subset=['fields.name'])
    dflyonclean = dflyonclean.rename(columns={'fields.name':'Name','fields.geo_shape.coordinates':'Geo','fields.status':'Available','fields.bike_stand':'Size'})

    # set the 'Available' column with boolean
    dflyonclean['Available'] = dflyonclean['Available'].replace("OPEN","True")

    for i, row in dflyonclean.iterrows():
        if not row['Available'] == 'True':
            dflyonclean['Available'].loc[i] = 'False'
    
    return(dflyonclean)

dflyonclean = clean_lyon(dflyon)
dflyonclean.head()

,Name,Geo,Available,Size
0,ZAC de la Buire,"[4.859863339774901, 45.75379945822723]",True,35
1,Brotteaux,"[4.859070556738342, 45.768412261376376]",True,20
2,Place Sainte Anne,"[4.865441659195344, 45.75695497472745]",True,18
3,Lafayette / Cr√©qui,"[4.847137408952479, 45.76340457257395]",True,16
4,Pr√©ssens√© / 8 mai 1945,"[4.896723707091346, 45.76918019445715]",False,16

In [16]:
def clean_paris(dfparis):
    dfparisclean = dfparis[["fields.name","fields.coordonnees_geo","fields.is_renting","fields.capacity"]].drop_duplicates(subset=['fields.name'])
    dfparisclean = dfparisclean.rename(columns={'fields.name':'Name','fields.coordonnees_geo':'Geo','fields.is_renting':'Available','fields.capacity':'Size'})

    # set the 'Available' column with boolean
    dfparisclean['Available'] = dfparisclean['Available'].replace("OUI","True")

    for i, row in dfparisclean.iterrows():
        if not row['Available'] == 'True':
            dfparisclean['Available'].loc[i] = 'False'
            
    return(dfparisclean)
            
dfparisclean = clean_paris(dfparis)
dfparisclean.head()

C:\Users\avere\.conda\envs\velomongo\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

,Name,Geo,Available,Size
0,Andr√© Mazet - Saint-Andr√© des Arts,"[48.8537558106, 2.33909580857]",True,55
1,Charonne - Robert et Sonia Delauney,"[48.855907556, 2.39257067442]",True,20
2,Jourdan - Stade Charl√©ty,"[48.8194283334, 2.34333537519]",True,60
3,Jouffroy d'Abbans - Wagram,"[48.8819732984, 2.30113215744]",True,40
4,Guersant - Gouvion-Saint-Cyr,"[48.8828777518, 2.28766737081]",True,39

In [17]:
len(dflilleclean)+len(dfrennesclean)+len(dflyonclean)+len(dfparisclean)

2044

### Concat

In [18]:
dfall = pd.concat([dflilleclean,dfrennesclean,dflyonclean,dfparisclean],ignore_index=True)

In [19]:
dfall.head()

                  Name                    Geo    TPE Available Size
0    HOPITAL MILITAIRE   [50.63393, 3.061687]   True      True   16
1           RUE ROYALE    [50.64031, 3.05774]   True      True   24
2             TANNEURS  [50.635014, 3.064802]   True      True   36
3         ST SEBASTIEN  [50.647236, 3.059376]   True      True   20
4  PLACE DE LA GARONNE  [50.612635, 3.059261]  False      True   12

### Live

In [28]:
import re

def send_live():
    """
    Mise √† jour live
    """
    # collect data
    ac = api_connector()    
    dflille = pd.json_normalize(ac.get_lille())[["fields.nbvelosdispo","fields.nbplacesdispo","fields.datemiseajour",'fields.geo']]
    dflille = dflille.rename(columns={'fields.nbvelosdispo':'availbalebike','fields.nbplacesdispo':'availableplaces',"fields.datemiseajour":'datemaj','fields.geo':'idstation'})
    
    # change geo to id station
    idlist = []
    for i, row in dflille.iterrows():
        idlist.append(re.sub('[\W\_]', "", str(row['idstation'])))
    dflille['idstation'] = idlist
    
    return(dflille)
    
send_live().head()

   availbalebike  availableplaces                    datemaj        idstation
0              2               14  2020-10-12T10:30:06+00:00   50633933061687
1              3               17  2020-10-12T10:30:05+00:00  506472363059376
2              9                3  2020-10-12T10:30:06+00:00  506126353059261
3             11               13  2020-10-12T10:30:06+00:00  506791233155906
4             13               11  2020-10-12T10:30:05+00:00    5064031305774